### PR TITLE
Add pointer() method for ROCArray and some library tests

### PR DESCRIPTION
**Pull request by torrance**
This PR mean to resolve [issue](https://github.com/JuliaGPU/AMDGPU.jl/issues/319) by providing a `Base.pointer(::ROCArray)` method that correctly handles non-zero offsets.

(Honestly, I don't understand how the calls to `pointer(::ROCArray)` were working at all before??!)

Currently, the FFT test now passes, however, the the BLAS test still fails. Still attempting to work out why `pointer()` is not being called when performing matrix multiplication.

### CODE REVIEW

**Comment by pxl-th** [comment]
> Still attempting to work out why pointer() is not being called when performing matrix multiplication.

Probably because we pass raw buffer pointer (`x.buf`) instead of calling `pointer(x)`

**Comment by torrance** [comment]
Ok, so I understand now how this was working in the first place: the calls to `pointer()` were ultimately calling `unsafe_convert(Ptr{T}, ::ROCArray{T})`. Fixing this function instead means explicit calls to `pointer()` as well as implicit conversions to pointer as part of `ccall()` now work.

This also resolves the BLAS bug.

I think this should be ready to merge. @jpsamaroo can you review this small change?

**Comment by pxl-th** [comment]
We probably should also check (and error?) if the view results in non-contiguous array, like following:

```julia
julia> x = AMDGPU.rand(Float32, 16, 16, 2);

julia> @view(x[4:8, 4:8, 1]) * @view(x[4:8, 4:8, 1])
ERROR: ReadOnlyMemoryError()
```

and allow views that only offest from the beginning.

**Comment by jpsamaroo** [comment]
Thanks @torrance ! @pxl-th let's add that in a separate PR.

**Pull request merged**
