### PR TITLE
Test multiple GPUArrays versions

### PR DESCRIPTION
**Pull request by jpsamaroo**

### CODE REVIEW

**Comment by jpsamaroo** [comment]
@maleadt is this because my branch wasn't made directly on the julia-test repo? If so, how can I work around that?

**Comment by maleadt** [comment]
Ah yes. I've given you write permisions to create a branch.

**Comment by jpsamaroo** [comment]
Awesome, thanks! Seems like it's working :smile:

**Comment by maleadt** [comment]
Looks good! Out of curiosity, why test multiple GPUArrays versions?

**Comment by jpsamaroo** [comment]
This lets me just keep adding GPUArrays versions to the bounds and not worry about whether all specified versions still work, because CI will ideally tell me so :slightly_smiling_face:

**Comment by jpsamaroo** [comment]
And CI agrees: GPUArrays 6 and 7 fail on `randn!(rng::GPUArrays.RNG, A::ROCVector{Float32})`. Should (probably) be easy to fix.

**Pull request merged**
