### PR TITLE
Rocsparse Support for AMDGPU.jl

### PR DESCRIPTION
**Pull request by matinraayai**
@jpsamaroo this is my somewhat working branch of the rocsparse port. Please see if you are able to debug the ```broadcast.jl``` and ```linalg.jl``` tests in the rocsparse folder.

### CODE REVIEW

**Comment by amontoison** [comment]
@matinraayai 
Any update on this PR?
I'm quite interested by the sparse matrix * dense vector products.

**Comment by matinraayai** [comment]
@jpsamaroo should debug two kernels in the tests that segfault. Otherwise it should be go.

**Comment by jpsamaroo** [comment]
Not yet, but mostly because we're working on getting #374 merged first, which will bring a bunch of fixes and a more consistent system for dealing with HIP. There are outstanding synchronization bugs with this PR, but I suspect that they'll be easily fixable once task support is merged.

**Comment by matinraayai** [comment]
@pxl-th can you take a look at the generic tests for rocsparse? There still might be some timing issues with HIP. I'm trying to get to the bottom of it.

**Comment by pxl-th** [comment]
I'll take a look at it shortly!

**Comment by pxl-th** [comment]
Superseded by #463.

**Pull request closed without merging**
