### PR TITLE
Support GPUCompiler 0.12

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@jpsamaroo can I punt this too you? 

```
Exceptions: Test Failed at /var/lib/buildkite-agent/builds/2-helios-jpsamaroo-me/julialang/amdgpu-dot-jl/test/device/exceptions.jl:15
--


   Evaluated: occursin("BoundsError", "julia_throw_boundserror_27520")
```

https://github.com/JuliaGPU/GPUCompiler.jl/compare/v0.11.5...v0.12.0

**Comment by jpsamaroo** [comment]
For sure, I was planning to finish it later today.

**Comment by jpsamaroo** [comment]
Oh this is actually working fine. I'll fix up a few of the tests that broke with recent GPUCompiler changes (the change in kernel exception strings, and something to do with `abs`), but otherwise this is ready to merge.

**Comment by jpsamaroo** [comment]
The tests don't significantly deviate from the latest master CI, so this was good to go. I'll fix those test issues in a separate PR.

Thanks @vchuravy !

**Pull request merged**
