### PR TITLE
Make build failure logging more verbose

### LINKED ISSUE #179: No warning when we fail to find ld.lld, and general build observability
We don't have any idea that it was `ld.lld` that we failed to find. Also, generally, it would be nice if we could expose more information about *why* the various build steps failed.

### PR DESCRIPTION
**Pull request by jpsamaroo**
Closes #179

### CODE REVIEW

**Comment by koehlerson** [comment]
```
(@v1.6) pkg> rm AMDGPU                                                                                                                                         
    Updating `~/.julia/environments/v1.6/Project.toml`                                                                                                         
  [21141c5a] - AMDGPU v0.2.16                                                                                                                                  
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`                                                                                                     
                                                                                                                                                               
(@v1.6) pkg> add AMDGPU#jps/verbose-build-fail                                                                                                                 
    Updating git-repo `https://github.com/JuliaGPU/AMDGPU.jl.git`                                                                                              
    Updating registry at `~/.julia/registries/General`                                                                                                         
   Resolving package versions...                                                                                                                               
    Updating `~/.julia/environments/v1.6/Project.toml`                                                                                                         
  [21141c5a] + AMDGPU v0.2.16 `https://github.com/JuliaGPU/AMDGPU.jl.git#jps/verbose-build-fail`                                                               
    Updating `~/.julia/environments/v1.6/Manifest.toml`                                                                                                        
  [21141c5a] ~ AMDGPU v0.2.16 ⇒ v0.2.16 `https://github.com/JuliaGPU/AMDGPU.jl.git#jps/verbose-build-fail`                                                     
    Building AMDGPU → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/dc0e60df251c50ca544e9d3d7202a5fc9d9c890c/build.log`                         
Precompiling project...                                                                                                                                        
  ✗ AMDGPU                                                                                                                                                     
  0 dependencies successfully precompiled in 12 seconds (66 already precompiled)                                                                               
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package 
```

log file
"Could not find ld.lld, please install it with your package manager"

**Comment by jpsamaroo** [comment]
What does `using AMDGPU` then give you?

**Comment by koehlerson** [comment]
```
(@v1.6) pkg> build AMDGPU
    Building AMDGPU → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/dc0e60df251c50ca544e9d3d7202a5fc9d9c890c/build.log`

julia> using AMDGPU
[ Info: Precompiling AMDGPU [21141c5a-9bdb-4563-92ae-f87d6854732e]
ERROR: LoadError: UndefVarError: librocblas not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/AMDGPU/axhD0/src/AMDGPU.jl:115
 [2] include
   @ ./Base.jl:386 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1235
 [4] top-level scope
   @ none:1
 [5] eval
   @ ./boot.jl:360 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [7] top-level scope
   @ none:1
in expression starting at /home/nneuhaus/.julia/packages/AMDGPU/axhD0/src/AMDGPU.jl:1
ERROR: Failed to precompile AMDGPU [21141c5a-9bdb-4563-92ae-f87d6854732e] to /home/nneuhaus/.julia/compiled/v1.6/AMDGPU/jl_B57PIZ.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1385
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1329
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1043
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:936
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:923
```

**Comment by koehlerson** [comment]
Tried it just now, so should be the latest commit
```julia-repl
➜ julia1.6
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.6) pkg> rm AMDGPU
    Updating `~/.julia/environments/v1.6/Project.toml`
  [21141c5a] - AMDGPU v0.2.16
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`

(@v1.6) pkg> add AMDGPU#jps/verbose-build-fail
     Cloning git-repo `https://github.com/JuliaGPU/AMDGPU.jl.git`
    Updating git-repo `https://github.com/JuliaGPU/AMDGPU.jl.git`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [21141c5a] + AMDGPU v0.2.16 `https://github.com/JuliaGPU/AMDGPU.jl.git#jps/verbose-build-fail`
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [21141c5a] ~ AMDGPU v0.2.16 ⇒ v0.2.16 `https://github.com/JuliaGPU/AMDGPU.jl.git#jps/verbose-build-fail`
    Building AMDGPU → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/ec92876dc469648e72a3048e471dc3604a0a0c46/build.log`
Precompiling project...
  2 dependencies successfully precompiled in 15 seconds (92 already precompiled, 1 skipped during auto due to previous errors)

julia> using AMDGPU
┌ Warning: ld.lld was not found, compilation functionality will be unavailable.
│ Please run Pkg.build("AMDGPU") and reload AMDGPU.
│ Reason: HIP runtime library not found
└ @ AMDGPU ~/.julia/packages/AMDGPU/cZSGX/src/AMDGPU.jl:207
┌ Warning: ROCm-Device-Libs were not found, device intrinsics will be unavailable.
│ Please run Pkg.build("AMDGPU") and reload AMDGPU.
│ Reason: unknown
└ @ AMDGPU ~/.julia/packages/AMDGPU/cZSGX/src/AMDGPU.jl:226

(@v1.6) pkg> build AMDGPU
    Building AMDGPU → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/ec92876dc469648e72a3048e471dc3604a0a0c46/build.log`
Precompiling project...
  ? ROCKernels
  1 dependency successfully precompiled in 9 seconds (92 already precompiled, 1 skipped during auto due to previous errors)
  1 dependency failed but may be precompilable after restarting julia

```

**Comment by jpsamaroo** [comment]
The `Reason:` message for lld should really say "ld.lld not found", but otherwise it seems like it's working correctly now. The device libs warning only shows up because the lld failure causes device libs searching to be skipped. I'll fix the message and then merge this then. Thanks for testing this @koehlerson !

**Pull request merged**
