### PR TITLE
Load bin deps during __init__

### LINKED ISSUE #43: Test code doesn't work
Hey!

I wanted to try AMDGPU.jl, but I fail at the first step at running a simple test code.
The problem:
I installed: [ROCm install Ubuntu](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu)
Then: `]add AMDGPU`

Then trieing to run this code: [Running-a-simple-kernel example](https://juliagpu.gitlab.io/AMDGPU.jl/quickstart/#Running-a-simple-kernel)
The run result: 
```
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty at ./Base.jl:33 [inlined]
 [2] getindex at ./refvalue.jl:32 [inlined]
 [3] HSAArray(::Array{Float64,1}) at /home/user/.julia/packages/AMDGPU/JBXsp/src/hsaarray.jl:34
 [4] top-level scope at /home/user/repo/amd_test/tests/test_AMD.jl:9
 [5] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
 [6] include_string(::Module, ::String, ::String) at ./loading.jl:1096
```
on the first AMDGPU line: 
`a_d = AMDGPU.HSAArray(a)`

I have ubuntu 20.04 and running this test on multiple Radeon VII. 

I think the problem should be pretty trivial since ]test AMDGPU throws the same error.
```
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty at ./Base.jl:33 [inlined]
 [2] getindex at ./refvalue.jl:32 [inlined]
 [3] get_default_agent() at /home/user/.julia/packages/AMDGPU/JBXsp/src/agent.jl:109
 [4] top-level scope at /home/user/.julia/packages/AMDGPU/JBXsp/test/runtests.jl:28
 [5] include(::String) at ./client.jl:457
 [6] top-level scope at none:6
in expression starting at /home/user/.julia/packages/AMDGPU/JBXsp/test/runtests.jl:28
ERROR: Package AMDGPU errored during testing
```

Does anyone know what do I do wrong?

### PR DESCRIPTION
**Pull request by jpsamaroo**
Hopefully fixes #43 

Not sure why this is necessary (since regenerating the `ext.jl` files should cause a recompile), but it seems to fix the bad behavior for me.

@Cvikli can you please test that this branch fixes the issue you're encountering?

### CODE REVIEW

**Comment by Cvikli** [comment]
Can you please provide me some details about how should I run the tests?

**Comment by jpsamaroo** [comment]
What error do you get? Right now the build step is pretty verbose, and if you don't have *every* optional dependency installed, it will look like it failed to build (even though HSA is working, which is all you really need).

**Comment by jpsamaroo** [comment]
Merged in #32

**Comment by jpsamaroo** [comment]
@Cvikli AMDGPU.jl v0.2.0 is in the process of being released, which has these changes.

**Comment by Cvikli** [comment]
Ping me and I am here for you! 

We have a lot of AMD GPU, would be nice if we would be able to use!

**Pull request closed without merging**
